name: FFAHardCore
version: ${project.version}
main: net.craftions.ffahardcore.FFAHardCore
api-version: 1.16
authors: [ MCTzOCK ]
load: POSTWORLD
database: false
commands:
  admin:
    usage: /<command> <setspawn|tpspawn>
    permission: craftions.ffahardcore.command.admin
permissions:
  craftions.ffahardcore.command.admin:
    description: You need this permission to run the /admin command
  craftions.ffahardcore.drop.bypass:
    description: You need this permission to drop items
  craftions.ffahardcore.inventory.bypass:
    description: You need this permission to use your inventory